import { type FullPageData } from '@/types';

// ============================================================
// MOCK DATA — used when Supabase is not configured
// Replace with real Supabase data by adding credentials to .env.local
// ============================================================

export const MOCK_PAGE_DATA: FullPageData = {
  page: {
    id: 'mock-page-1',
    user_id: 'mock-user-1',
    slug: 'nayan-charan',
    title: 'Nayan ❤️ Charan',
    subtitle: 'For the person who makes my world better every single day.',
    status: 'published',
    hero_name: 'Charan',
    partner_name: 'Charan',
    author_name: 'Nayan',
    relationship_start_date: '2022-06-12',
    relationship_start_time: '18:30',
    timezone: 'Asia/Kolkata',
    browser_title: 'Nayan ❤️ Charan — A Love Story',
    og_title: 'Nayan ❤️ Charan',
    og_description: 'I made something special just for you.',
    og_image_url: null,
    favicon_url: null,
    hero_message: 'I made a little something for you...',
    footer_text: 'Made with love by Nayan ❤️',
    music_url: null,
    music_autoplay: false,
    music_loop: true,
    bg_effects_enabled: true,
    bg_effects_type: 'hearts',
    bg_effects_density: 4,
    bg_effects_speed: 3,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  theme: {
    id: 'mock-theme-1',
    page_id: 'mock-page-1',
    bg_color: '#FFF1F4',
    primary_color: '#D94F73',
    secondary_color: '#9E2F50',
    card_color: '#FFFFFF',
    text_color: '#6B263C',
    muted_text_color: '#A76A7D',
    border_color: '#F3C8D3',
    button_color: '#D94F73',
    button_text_color: '#FFFFFF',
    heading_font: 'Playfair Display',
    body_font: 'Inter',
    border_radius: '16px',
    shadow_intensity: 'md',
    preset_name: 'Romantic Pink',
  },
  sections: [
    { id: 's1', page_id: 'mock-page-1', type: 'hero', title: 'Hero', enabled: true, order_index: 0, config: { heading: 'For My Love ❤️', subheading: 'Charan', message: 'I made a little something for you...', show_scroll_indicator: true }, created_at: new Date().toISOString() },
    { id: 's2', page_id: 'mock-page-1', type: 'secretReveal', title: 'Secret Reveal', enabled: true, order_index: 1, config: { title: "Aren't we cute? 👀", description: 'Click to reveal something special...', image_url: 'https://images.unsplash.com/photo-1518568814500-bf0f8d125f46?w=400', reveal_text: 'Tap to reveal ✨', post_reveal_message: 'We really are though 🥹' }, created_at: new Date().toISOString() },
    { id: 's3', page_id: 'mock-page-1', type: 'loveLetter', title: 'Love Letter', enabled: true, order_index: 2, config: { salutation: 'My Love,', body: '<p>I have been trying to find the right words for a long time now. And I realize — there are no perfect words. There is only this: you make everything better.</p><p>Every morning is better because you exist. Every laugh is louder. Every silence is warmer. You somehow turned all the ordinary moments into my favorite memories.</p><p>I don\'t know how you do it, but you make me feel like the luckiest person alive — just by being you.</p><p>Thank you for choosing me, every single day.</p>', closing: 'With all my heart,', signature: 'Nayan ❤️' }, created_at: new Date().toISOString() },
    { id: 's4', page_id: 'mock-page-1', type: 'timeline', title: 'Our Story', enabled: true, order_index: 3, config: { heading: 'Our Story', subtitle: 'Every chapter better than the last' }, created_at: new Date().toISOString() },
    { id: 's5', page_id: 'mock-page-1', type: 'timeTogether', title: 'Time Together', enabled: true, order_index: 4, config: { heading: 'Time Together', subtitle: 'Every second with you is a gift', start_date: '2022-06-12', start_time: '18:30', timezone: 'Asia/Kolkata' }, created_at: new Date().toISOString() },
    { id: 's6', page_id: 'mock-page-1', type: 'reasons', title: 'Things I Love About You', enabled: true, order_index: 5, config: { heading: 'Things I Love About You', subtitle: 'Here is a small portion of them', footer_note: '...and a hundred more I ran out of room for' }, created_at: new Date().toISOString() },
    { id: 's7', page_id: 'mock-page-1', type: 'quiz', title: 'Love Quiz', enabled: true, order_index: 6, config: { heading: 'How Well Do You Know Us? 💕', subtitle: 'Let\'s find out...', completion_message: 'You know us so well! 🥹' }, created_at: new Date().toISOString() },
    { id: 's8', page_id: 'mock-page-1', type: 'marriageGame', title: 'Will You Marry Me?', enabled: true, order_index: 7, config: { heading: 'One last question...', question: 'Will you marry me? 💍❤️', yes_button_text: 'YES ❤️', no_button_texts: ['NO 😈', 'Nice try 😏', 'Nope!', 'Are you sure? 😂', 'Wrong button!', 'You can\'t escape ❤️', 'You know there\'s only one answer 😌'], yes_celebration_title: 'She Said YES! ❤️', yes_celebration_subtitle: 'I knew you\'d choose correctly 😌', yes_celebration_body: 'Forever starts here. 💍' }, created_at: new Date().toISOString() },
    { id: 's9', page_id: 'mock-page-1', type: 'gallery', title: 'Photo Memories', enabled: true, order_index: 8, config: { heading: 'Our Memories 📸', subtitle: 'Every picture tells our story', layout: 'polaroid' }, created_at: new Date().toISOString() },
    { id: 's10', page_id: 'mock-page-1', type: 'spinWheel', title: 'Spin to Win', enabled: true, order_index: 9, config: { heading: 'Spin to Win! 🎡', subtitle: '7 things could happen next...', spin_button_text: 'SPIN ❤️', result_prefix: "Tonight's mission:" }, created_at: new Date().toISOString() },
    { id: 's11', page_id: 'mock-page-1', type: 'compatibility', title: 'Compatibility', enabled: true, order_index: 10, config: { heading: 'How Compatible Are We? ❤️', subtitle: 'The numbers don\'t lie...', name1: 'Nayan', name2: 'Charan' }, created_at: new Date().toISOString() },
    { id: 's12', page_id: 'mock-page-1', type: 'songs', title: 'Songs', enabled: true, order_index: 11, config: { heading: 'Songs That Remind Me of You 🎵', subtitle: 'Every melody is a memory' }, created_at: new Date().toISOString() },
    { id: 's13', page_id: 'mock-page-1', type: 'moonPhase', title: 'Moon Phase', enabled: true, order_index: 12, config: { heading: 'The Moon That Night 🌙', subtitle: 'Somehow, even the moon remembers that day.', date_mode: 'relationship' }, created_at: new Date().toISOString() },
    { id: 's14', page_id: 'mock-page-1', type: 'finalMessage', title: 'Final Message', enabled: true, order_index: 13, config: { heading: 'Thank You for Being with Me ❤️', body: '<p>Thank you for every laugh.</p><p>Every memory.</p><p>Every argument.</p><p>Every hug.</p><p>Every little moment.</p><p>I would choose you again.</p><p>And again.</p><p>And again.</p><p>Forever. ❤️</p>', signature: '— Nayan', show_hearts: true }, created_at: new Date().toISOString() },
  ],
  timeline_items: [
    { id: 't1', page_id: 'mock-page-1', date: '2022-06-12', title: 'The Beginning', description: 'The day everything started. The moment I met you, I knew something had changed forever. I just didn\'t know how to say it yet.', location: 'Hyderabad', emoji: '❤️', order_index: 0 },
    { id: 't2', page_id: 'mock-page-1', date: '2022-08-20', title: 'Our First Date', description: 'Nervous, excited, and completely unable to stop smiling. Every moment felt like something out of a movie.', location: 'Jubilee Hills', emoji: '🍽️', order_index: 1 },
    { id: 't3', page_id: 'mock-page-1', date: '2022-10-05', title: 'I Knew It Was You', description: 'There was this one evening when I looked at you and just knew. No doubt, no questions — just you.', location: 'Hussain Sagar', emoji: '✨', order_index: 2 },
    { id: 't4', page_id: 'mock-page-1', date: '2023-02-14', title: 'First Valentine\'s Together', description: 'Simple, beautiful, and everything I could have asked for. Being with you is my favorite thing.', emoji: '💝', order_index: 3 },
    { id: 't5', page_id: 'mock-page-1', date: '2024-01-01', title: 'Our First New Year Together', description: 'Watching the fireworks with you, I couldn\'t help but think — I want every year to start exactly like this.', emoji: '🎆', order_index: 4 },
  ],
  reasons: [
    { id: 'r1', page_id: 'mock-page-1', emoji: '😊', title: 'Your Smile', description: 'You somehow make every bad day better just by smiling. It\'s completely unfair how effective it is.', order_index: 0 },
    { id: 'r2', page_id: 'mock-page-1', emoji: '🤣', title: 'Your Laugh', description: 'Your laugh is my favorite sound in the entire world. I would do anything to hear it every day.', order_index: 1 },
    { id: 'r3', page_id: 'mock-page-1', emoji: '🫂', title: 'Your Hugs', description: 'Being in your arms feels like home. No matter how chaotic everything else is, that feeling never changes.', order_index: 2 },
    { id: 'r4', page_id: 'mock-page-1', emoji: '🧠', title: 'Your Mind', description: 'The way you think about things, the way you see the world — it challenges me, inspires me, and never stops surprising me.', order_index: 3 },
    { id: 'r5', page_id: 'mock-page-1', emoji: '💪', title: 'Your Strength', description: 'You handle hard things with so much grace. Even when you don\'t feel strong, you are — and I see it every single time.', order_index: 4 },
    { id: 'r6', page_id: 'mock-page-1', emoji: '🌸', title: 'Your Kindness', description: 'You have this quiet, genuine kindness that shows up in everything you do. It\'s one of the most beautiful things about you.', order_index: 5 },
    { id: 'r7', page_id: 'mock-page-1', emoji: '🎭', title: 'Your Goofiness', description: 'You have this ridiculous side that only I get to see, and I love every single bit of it. Don\'t ever change.', order_index: 6 },
    { id: 'r8', page_id: 'mock-page-1', emoji: '💫', title: 'Just... You', description: 'Everything. The whole package. I couldn\'t imagine anyone else, and I wouldn\'t want to.', order_index: 7 },
  ],
  memories: [
    { id: 'm1', page_id: 'mock-page-1', image_url: 'https://images.unsplash.com/photo-1522673607200-164d1b6ce486?w=400', caption: 'That evening we stayed out too late', date: '2022-09-10', location: 'Hyderabad', order_index: 0 },
    { id: 'm2', page_id: 'mock-page-1', image_url: 'https://images.unsplash.com/photo-1529333166437-7750a6dd5a70?w=400', caption: 'Laughing about nothing', date: '2022-11-15', order_index: 1 },
    { id: 'm3', page_id: 'mock-page-1', image_url: 'https://images.unsplash.com/photo-1518568814500-bf0f8d125f46?w=400', caption: 'A perfect ordinary day', date: '2023-03-22', order_index: 2 },
    { id: 'm4', page_id: 'mock-page-1', image_url: 'https://images.unsplash.com/photo-1516589091380-5d8e87df6999?w=400', caption: 'This one is my favorite', date: '2023-07-04', order_index: 3 },
    { id: 'm5', page_id: 'mock-page-1', image_url: 'https://images.unsplash.com/photo-1520854221256-17451cc331bf?w=400', caption: 'Remember this day?', date: '2023-12-25', order_index: 4 },
    { id: 'm6', page_id: 'mock-page-1', image_url: 'https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?w=400', caption: 'One of my favorite memories', date: '2024-02-14', order_index: 5 },
  ],
  songs: [
    { id: 'sg1', page_id: 'mock-page-1', title: 'Perfect', artist: 'Ed Sheeran', description: 'This one always reminds me of us.', youtube_url: 'https://www.youtube.com/watch?v=2Vv-BfVoq4g', order_index: 0 },
    { id: 'sg2', page_id: 'mock-page-1', title: 'Thousand Years', artist: 'Christina Perri', description: 'A thousand years, I\'ll love you for a thousand more.', youtube_url: 'https://www.youtube.com/watch?v=rtOvBOTyX00', order_index: 1 },
    { id: 'sg3', page_id: 'mock-page-1', title: 'All of Me', artist: 'John Legend', description: 'Because you\'ve got all of me, and I\'ve got all of you.', youtube_url: 'https://www.youtube.com/watch?v=450p7goxZqg', order_index: 2 },
    { id: 'sg4', page_id: 'mock-page-1', title: 'Can\'t Help Falling in Love', artist: 'Elvis Presley', description: 'Wise men say, only fools rush in — but I couldn\'t help it.', youtube_url: 'https://www.youtube.com/watch?v=vGJTaP6anOU', order_index: 3 },
    { id: 'sg5', page_id: 'mock-page-1', title: 'The Power Of Love', artist: 'Céline Dion', description: 'Pure and powerful — just like what I feel for you.', youtube_url: 'https://www.youtube.com/watch?v=Y8HOfcYWZoo', order_index: 4 },
  ],
  game_questions: [
    { id: 'q1', page_id: 'mock-page-1', question: 'Who fell in love first? 👀', order_index: 0, type: 'quiz', answers: [
      { id: 'a1', question_id: 'q1', text: 'Nayan', is_correct: true, response_message: 'Obviously 😌 I was gone the moment I met you.', order_index: 0 },
      { id: 'a2', question_id: 'q1', text: 'Charan', is_correct: false, response_message: 'Nice try 😄 but we both know the answer.', order_index: 1 },
    ]},
    { id: 'q2', page_id: 'mock-page-1', question: 'Who texts first most of the time? 📱', order_index: 1, type: 'quiz', answers: [
      { id: 'a3', question_id: 'q2', text: 'Nayan', is_correct: true, response_message: 'Because I can\'t go too long without talking to you 🥹', order_index: 0 },
      { id: 'a4', question_id: 'q2', text: 'Charan', is_correct: false, response_message: 'Sometimes! But usually it\'s me 😄', order_index: 1 },
    ]},
    { id: 'q3', page_id: 'mock-page-1', question: 'What is Nayan\'s love language? 💕', order_index: 2, type: 'quiz', answers: [
      { id: 'a5', question_id: 'q3', text: 'Words of Affirmation', is_correct: false, response_message: 'Close! But not quite 😊', order_index: 0 },
      { id: 'a6', question_id: 'q3', text: 'Quality Time', is_correct: true, response_message: 'Yes! I just want to be with you 🥰', order_index: 1 },
      { id: 'a7', question_id: 'q3', text: 'Acts of Service', is_correct: false, response_message: 'Not quite, keep trying!', order_index: 2 },
    ]},
    { id: 'q4', page_id: 'mock-page-1', question: 'Where did we go on our first date? 🍽️', order_index: 3, type: 'quiz', answers: [
      { id: 'a8', question_id: 'q4', text: 'Jubilee Hills', is_correct: true, response_message: 'You remember! That evening was perfect 🥹', order_index: 0 },
      { id: 'a9', question_id: 'q4', text: 'Banjara Hills', is_correct: false, response_message: 'Not quite! Try again 😄', order_index: 1 },
      { id: 'a10', question_id: 'q4', text: 'Hitech City', is_correct: false, response_message: 'Nope! Think harder 😊', order_index: 2 },
    ]},
  ],
  wheel_items: [
    { id: 'w1', page_id: 'mock-page-1', text: 'Movie Night', emoji: '🎬', weight: 1, result_message: 'Pick a movie together and cuddle up! 🍿', color: '#D94F73', order_index: 0 },
    { id: 'w2', page_id: 'mock-page-1', text: 'Dinner Date', emoji: '🍝', weight: 1, result_message: 'Time to dress up and go somewhere nice! 🥂', color: '#9E2F50', order_index: 1 },
    { id: 'w3', page_id: 'mock-page-1', text: 'Cuddle Time', emoji: '❤️', weight: 2, result_message: 'The best activity of all — just us 🥰', color: '#F472B6', order_index: 2 },
    { id: 'w4', page_id: 'mock-page-1', text: 'Surprise Gift', emoji: '🎁', weight: 1, result_message: 'Nayan owes you a surprise gift! 🎊', color: '#EC4899', order_index: 3 },
    { id: 'w5', page_id: 'mock-page-1', text: 'Long Drive', emoji: '🚗', weight: 1, result_message: 'Windows down, music up, just us! 🌙', color: '#BE185D', order_index: 4 },
    { id: 'w6', page_id: 'mock-page-1', text: 'Ice Cream', emoji: '🍦', weight: 1, result_message: 'Ice cream run! You pick the flavor 🍧', color: '#F9A8D4', order_index: 5 },
    { id: 'w7', page_id: 'mock-page-1', text: 'Your Choice', emoji: '😌', weight: 1, result_message: 'You decide! Whatever you want, we\'ll do it 💕', color: '#FBCFE8', order_index: 6 },
  ],
  compatibility_items: [
    { id: 'c1', page_id: 'mock-page-1', label: 'Love', percentage: 100, order_index: 0 },
    { id: 'c2', page_id: 'mock-page-1', label: 'Humour', percentage: 97, order_index: 1 },
    { id: 'c3', page_id: 'mock-page-1', label: 'Adventure', percentage: 94, order_index: 2 },
    { id: 'c4', page_id: 'mock-page-1', label: 'Cuteness', percentage: 100, order_index: 3 },
    { id: 'c5', page_id: 'mock-page-1', label: 'Chaos', percentage: 99, order_index: 4 },
  ],
};
